# Generated by Django 5.1.4 on 2025-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreyash_app', '0002_alter_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('roll_no', models.IntegerField(max_length=10)),
                ('contect', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('image_new', models.ImageField(upload_to=None)),
            ],
        ),
    ]
