# Generated by Django 5.1.4 on 2025-01-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shreyash_app', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image_new',
        ),
    ]
