# Generated by Django 5.1.4 on 2025-01-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreyash_app', '0004_remove_student_image_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_price', models.IntegerField(max_length=10)),
                ('course_date', models.DateField()),
                ('course_batch_student_numbers', models.IntegerField(max_length=100)),
            ],
        ),
    ]
