# Generated by Django 5.1.4 on 2025-01-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreyash_app', '0005_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(default='default.jpg', upload_to='courses_image/'),
        ),
    ]
