# Generated by Django 5.1.4 on 2025-01-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreyash_app', '0007_alter_courses_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(default='default.jpg', upload_to='courses_image/'),
        ),
    ]
