# Generated by Django 4.2.17 on 2025-01-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreyash_app', '0011_alter_courses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(upload_to='cours/'),
        ),
    ]
