# Generated by Django 4.2.17 on 2025-01-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreyash_app', '0012_alter_courses_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_description',
            field=models.TextField(default='This is course description', max_length=500),
        ),
    ]
